apiVersion: v1
kind: Pod
metadata:
  name: openai-demo
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: abiancu/openai-demo:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000