name: CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login in to Docker Hub
        run: |
          echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t openai-demo:latest -f Dockerfile .

      - name: Push Image to Docker Repo
        run: |
          docker tag openai-demo:latest ${{secrets.DOCKERHUB_USERNAME}}/openai-demo:latest
          docker push ${{secrets.DOCKERHUB_USERNAME}}/openai-demo:latest

      - name: Create key json file
        uses: jsdaniell/create-json@1.1.2
        with:
         name: key.json
         json: ${{secrets.GCR_KEY}}
     
      - name: Authenticate with GCR
        run: |
          cat key.json | docker login -u _json_key --password-stdin https://gcr.io
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker
       

      - name: Push Docker image to container
        run: |
           docker tag openai-demo:latest gcr.io/${{secrets.GOOGLE_PROJECT_ID}}/openai-demo:latest
           docker push gcr.io/${{secrets.GOOGLE_PROJECT_ID}}/openai-demo:latest