name: CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login in to Docker Hub
        run: |
          echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t openai-demo:latest -f Dockerfile .

      - name: Push Image to Docker Repo
        run: |
          docker tag openai-demo:latest ${{secrets.DOCKERHUB_USERNAME}}/openai-demo:latest
          docker push ${{secrets.DOCKERHUB_USERNAME}}/openai-demo:latest

      - name: Authenticate with GCR
        uses: Dockerfile .
        with:
          registry: gcr.io
          username: _json_key
          password: ${{secrets.GCP_SERVICE_AUTH_KEY}}

      - name: Push Docker image to container
        run: |
           docker tag openai-demo:latest gcr.io/${{secrets.GOOGLE_PROJECT_ID}}/openai-demo:latest
           gcloud docker -- push gcr.io/${{secrets.GOOGLE_PROJECT_ID}}/openai-demo:latest